-- ============================================================
-- Schema v4 — Run this in Supabase SQL Editor
-- Stores quarterly "lessons learned" summaries generated by
-- scripts/run_quarterly_review.py. The latest row gets injected as
-- extra context into every weekly/monthly prompt going forward, so
-- the agent reads its own past mistakes before making new calls.
-- ============================================================

CREATE TABLE IF NOT EXISTS model_lessons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    period_label TEXT,
    decisions_analyzed INT,
    lessons_text TEXT
);
